### ISSUE TITLE
dependency error at start

### ISSUE THREAD

**Issue by seralf** [italia/daf-semantic-triplifier#1]
```bash
#### HTTP START with configuration:
2019-03-29 12:15:03 INFO  it.almawave.kb.http.HTTP:104 - http://0.0.0.0:7777/kb/api/v1
####################
2019-03-29 12:15:03 DEBUG triplifier.endpoints.RepoService:27 - #### REPOSITORY SERVICE
2019-03-29 12:15:03 INFO  repository.triplestore.MockRepo:89 - #### RDF repository START
2019-03-29 12:15:03 DEBUG org.openrdf.sail.memory.MemoryStore:264 - Initializing MemoryStore...
2019-03-29 12:15:03 DEBUG org.openrdf.sail.memory.MemoryStore:334 - MemoryStore initialized
2019-03-29 12:15:03 INFO  it.almawave.kb.http.HTTP:161 - #### HTTP - START
Mar 29, 2019 12:15:06 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 2
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.8.9 requires Jackson Databind version >= 2.8.0 and < 2.9.0
	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:66)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:18)
...
```

**Comment by seralf** [comment]
this seems to be related to conflict with jackson version

**Comment by giorgialodi** [comment]
@seralf looking at the Web it seems that with some dependencies defined in the porn.xml we may fix it. Strange that it does not apply to you. Probably because you are on a windows or linux environment? We are both under MAC OSX

**Comment by giorgialodi** [comment]
I have fixed in my configuration adding the following dependency in the pom.xml

<dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-scala_2.11</artifactId>
            <version>2.8.8</version>
    </dependency>

If this is the problem, I guess we need to act accordingly in the overall repo

**Comment by seralf** [comment]
thanks Giorgia

ok, it should be fixed with the last commit: this is again a problem related to the lack of a manager for the project dependencies, so the workaround was:
- producing an uber jar for the http part
- copy that under a local lib folder
- add the explicit references for most recent jackson lib in the pom.xml

I'll close this issue, then add the lastest jar under the pseudo-maven repository I've added at:
https://github.com/italia/daf-semantics/tree/master/mvn

(in case at some point someone would use it as the external maven repository)
